version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies

  pre_build:
    commands:
      - echo Pre Build Phase

  build:
    commands:
      - echo Build Started
      - npm run build

  post_build:
    commands:
      - echo Build Completed

artifacts:
  files:
    - '**/*'
